fix comparing types and use isinstance
canonical/operator-libs-linux pull request #105
Opened 2023-08-15 11:11 UTC by rgildein

Replace types comparison with usage of `isinstance` function.

2023-08-15 22:42 UTC, benhoyt requested changes
Won't the patch versions need incrementing due to these changes?

2023-08-15 22:42 UTC, benhoyt commented on tests/unit/test_passwd.py
> +            print(passwd.user_exists(True))
Is this left-over debugging?

2023-08-15 22:42 UTC, benhoyt commented
Other than that, though, this looks good to me -- thanks!

2023-08-17 02:39 UTC, NucciTheBoss commented
This pull request should fix the failing lint tests in https://github.com/canonical/operator-libs-linux/pull/106

2023-08-22 21:18 UTC, benhoyt commented on tests/unit/test_passwd.py
> +            print(passwd.user_exists(True))
```suggestion
            passwd.user_exists(True)
```

2023-08-22 22:07 UTC, benhoyt approved these changes

2023-08-22 22:08 UTC, merged

2023-08-30 12:44 UTC, rgildein commented on tests/unit/test_passwd.py
> +            print(passwd.user_exists(True))
Yes, sorry for that