apt.py: use subprocess.run with check=True instead of check_call when capturing stdout and stderr
canonical/operator-libs-linux pull request #114
Opened 2023-12-14 19:28 UTC by Perfect5th

It's inadvisable to use `check_call` with `stdout=PIPE` and `stderr=PIPE`, as the child process will block if enough output is generated (see Note in https://docs.python.org/3/library/subprocess.html#subprocess.check_call)

We've seen some hanging subprocesses in the `landscape-server` charm due to this (and other, already addressed issues): https://bugs.launchpad.net/landscape/+bug/2033091

This change uses `subprocess.run` instead, with `capture_output=True` and `check=True`. Behaviour should be the same, except avoiding the aforementioned blocking issue.

2023-12-14 19:43 UTC, tonyandrewmeyer approved these changes
Thanks, LGTM!

2023-12-14 19:52 UTC, benhoyt requested changes
Thanks! Changes look good to me, however, we need to bump up the `LIBPATCH` version here: https://github.com/canonical/operator-libs-linux/blob/a1b80b35514b2b1358745f04635596a81eaf7810/lib/charms/operator_libs_linux/v0/apt.py#L125

2023-12-14 19:55 UTC, benhoyt approved these changes
Excellent, thanks! `subprocess.run` is nice!

2023-12-14 20:11 UTC, merged

2023-12-14 20:44 UTC, benhoyt commented
Separately, I've noticed that we're using `e.output` (stdout) in the exception messages, meaning that the actual error message doesn't get included in the output here, it just says "None". See https://github.com/canonical/operator-libs-linux/issues/113. We'll fix that separately.

2023-12-14 20:51 UTC, benhoyt commented
That said, @Perfect5th, if you would like to submit a PR to use `e.stderr` in those exceptions, go ahead. :-)

(I notice that this change will mean that `e.output` is `b''` instead of `None`, but that doesn't help much.)

2023-12-15 00:06 UTC, Perfect5th commented
See #115