Add ability to install snap by revision
canonical/operator-libs-linux pull request #88
Opened 2023-03-31 19:37 UTC by shayancanonical

## Issue
We are now able to install snaps by revisions, but the snap charm library does not yet support this flag.

We would like to add support for the `--revision` flag so that we can pin our snap versions in charms.

## Solution
Add optional kwarg `revision` to the `ensure`, `_install` and `_refresh` methods of Snap in the snap charm lib

2023-04-01 07:44 UTC, jnsgruk requested changes
A minor data type nit, and two things to consider:

- How does revision interact with channel when both are specified? 
- This needs both unit and integration tests before merging

Otherwise thanks for the contribution!

2023-04-01 07:44 UTC, jnsgruk commented on lib/charms/operator_libs_linux/v1/snap.py
> +        self, channel: Optional[str] = "", cohort: Optional[str] = "", revision: Optional[str] = ""
Strikes me that revision should be `int` throughout?

2023-04-03 09:43 UTC, jnsgruk commented
Gonna take a look at this later, @PietroPasotti and @marcoppenheimer could you also cast an eye over this?

2023-04-03 11:41 UTC, shayancanonical commented
Re specifying both `revision` and `channel`: I tested locally, and discovered that `revision` always takes precedence when both are specified. I was leaning towards keeping the lib lean and allowing users to specify both (and let the underlying `snap install` command determine how to resolve a mismatch). However, I am also open to adding validation to this lib to ensure both are not specified simultaneously

2023-04-03 11:45 UTC, jnsgruk commented
In that case I'd leave the lib clean, but update the doc strings to make the behaviour documented at least

2023-04-03 12:30 UTC, marcoppenheimer approved these changes
LGTM, no issues that I can see! Solid implementation 👍🏾

2023-04-03 14:05 UTC, jnsgruk approved these changes
LGTM, thanks.

Looks like the docstrings need some work for consistency in this lib (around wording/convention for optionality etc. Will open a separate issue)

2023-04-03 14:06 UTC, merged